
// the function given below is to show all the data from main page, It shows sprinkles boxes and buttons. 
// It also hide them when all the work is done
function Show_content(){
	
	 var x = document.getElementById("myDIV");
  if (x.style.display === "none") {
    x.style.display = "block";
  } else {
    x.style.display = "none";
  }
  clearData();
  y = document.getElementById("header1");
  
  if (y.style.display === "none") {
    y.style.display = "block";
  } else {
    y.style.display = "none";
  }
	
}

// the function given below is called by clicking on reset button, 
//it clears all the data from text fields and reset selected sprinkles
// It also hide the circular data that is shown after clicking on submit button
function clearData(){
	
	document.getElementById("myform").reset();
	
	document.getElementById("result").style.display = "none";
}

// this function is called after clicking on submit button to show circular tabs as well as
// calls weather function to display real time weather condition
function submit(){
	weatherBallon( 2166025 );
	 document.getElementById("result").style.display = "block";
 
}


// weather condition and temperature function
// key is generated by creating account in openweathermap.org
// This is done by using API which takes city id as parameter
// It returns data in xml form which is then fetched out and is fed to html tag to display.
const key = 'f5641fec30ab866630361503d27f6ca7';
if(key=='') document.getElementById('temp').innerHTML = ('Remember to add your api key!');

function weatherBallon( cityID ) {
	fetch('https://api.openweathermap.org/data/2.5/weather?id=' + cityID+ '&appid=' + key)  
	.then(function(resp) { return resp.json() }) // Convert data to json
	.then(function(data) {
		drawWeather(data);
	})
	.catch(function() {
		// catch any errors
	});
}
function drawWeather( d ) {
	
	// below code converts temperature to degree celcius from kelvin scale.
  var celcius = Math.round(parseFloat(d.main.temp)-273.15);
	var fahrenheit = Math.round(((parseFloat(d.main.temp)-273.15)*1.8)+32);
  var description = d.weather[0].description; 
	//below line embed the data to an html tag with id temp
	document.getElementById('temp').innerHTML = description+"<br>"+celcius+'&deg;'+"<br>"+d.name;
	
}